---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod-1-24-2
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istiod
      version: 1.24.2+tetrate1
      sourceRef:
        kind: HelmRepository
        name: istio-v2
        namespace: qa-flux
  interval: 5m
  values:
    global:
      hub: istio/multiarch
      tag: 1.24.2-tetrate-v1
      
      configValidation: true
      imagePullSecrets:
      - pullbot
      proxy:
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sleep
                - '45'
      
    
    revision: 1-24-2
    
    meshConfig:
      accessLogFile: /dev/stdout
      discoverySelectors:
      - matchLabels:
          istio-discovery: enabled
    
    pilot:
      autoscaleEnabled: true
      autoscaleMin: 2
      autoscaleMax: 5
     
      env:
        PILOT_SIDECAR_ENABLE_INBOUND_TLS_V2: "true"
        PILOT_HTTP10: 1
