{{- if index (datasource "input").foundation "istio" -}}
{{- $istio := index (datasource "input").foundation.istio "version" -}}
{{- $bu := index (datasource "input").cluster.businessUnit -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod-{{ index (datasource "input").foundation.istio.version | strings.ReplaceAll "." "-" }}
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-support
      namespace: bootstrap
  chart:
    spec:
      chart: istiod
      {{- if eq $istio "1.16.4" }}
      version: {{ index (datasource "input").foundation.istio.version }}
      {{- else if eq $istio "1.18.2" }}
      version: {{ index (datasource "input").foundation.istio.version }}
      {{- else if eq $istio "1.18.5" }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
      {{- else if eq $istio "1.20.2" }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
      {{- else if eq $istio "1.20.3" }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v1
      {{- else if eq $istio "1.24.2" }}
      version: {{ index (datasource "input").foundation.istio.version }}+tetrate1
      {{- else }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
      {{- end }}
      sourceRef:
        kind: HelmRepository
        name: {{ if eq $istio "1.24.2" }}istio-v2{{ else }}istio{{ end }}
        namespace: infrastructure-{{ index (datasource "input").cluster.environment }}-fluxsystem
  interval: 5m
  values:
    global:
      hub: infacloud-ct-docker.jfrog.io/foundation/istio/multiarch
      {{- if eq $istio "1.16.4" }}
      tag: {{ index (datasource "input").foundation.istio.version }}-tetrate-v1
      {{- else if eq $istio "1.18.2" }}
      tag: {{ index (datasource "input").foundation.istio.version }}-tetrate-v0
      {{- else if eq $istio "1.18.5" }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
      {{- else if eq $istio "1.20.2" }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
      {{- else if eq $istio "1.20.3" }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v1
      {{- else if eq $istio "1.24.2" }}
      tag: {{ index (datasource "input").foundation.istio.version }}-tetrate-v1
      {{- else }}
      tag: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
      {{- end }}
      configValidation: true
      imagePullSecrets:
      - tpcdeploybot
      {{- if ne "abc" ($bu) }}
      proxy:
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/sleep
                - '45'
      {{- end }}

    revision: {{ index (datasource "input").foundation.istio.version | strings.ReplaceAll "." "-" }}

    meshConfig:
      accessLogFile: /dev/stdout
      discoverySelectors:
      - matchLabels:
          istio-discovery: enabled

    pilot:
      autoscaleEnabled: true
      autoscaleMin: 2
      autoscaleMax: 5

      env:
        PILOT_SIDECAR_ENABLE_INBOUND_TLS_V2: "true"
        PILOT_HTTP10: 1
        {{- if eq "abc" ($bu) }}
        PILOT_PUSH_THROTTLE: "1"
        PILOT_DEBOUNCE_AFTER: "60s"
        PILOT_DEBOUNCE_MAX: "70s"
        {{- end }}
      volumes:
        - name: istio-fail-if-cacerts-absent
          secret:
            secretName: cacerts
            optional: false
{{- end -}}
