{{- if index (datasource "input").foundation "istio" -}}
{{- $istio := index (datasource "input").foundation.istio "version" -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
{{- if eq $istio "1.16.4" }}
      version: {{ index (datasource "input").foundation.istio.version }}
{{- else if eq $istio "1.18.2" }}
      version: {{ index (datasource "input").foundation.istio.version }}
{{- else if eq $istio "1.18.5"}}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
{{- else if eq $istio "1.20.2" }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
{{- else if eq $istio "1.20.3" }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v1
{{- else if eq $istio "1.24.2" }}
      version: {{ index (datasource "input").foundation.istio.version }}+tetrate1
{{- else }}
      version: {{ index (datasource "input").foundation.istio.version }}-tetrate-v2
{{- end }}
      sourceRef:
        kind: HelmRepository
        name: {{ if eq $istio "1.24.2" }}istio-v2{{ else }}istio{{ end }}
        namespace: infrastructure-{{ index (datasource "input").cluster.environment }}-fluxsystem
  interval: 5m
  values:
    defaultRevision: {{ index (datasource "input").foundation.istio.version | strings.ReplaceAll "." "-" }}
{{- end -}}
