---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-support
  namespace: bootstrap
spec:
  dependsOn:
    - name: monitoringaddon
      namespace: lamm
  chart:
    spec:
      chart: istio-support
      version:  {{ index (datasource "input").foundation.istiosupport.version }}
      sourceRef:
        kind: HelmRepository
        name: ct-helm-virt
        namespace: infrastructure-{{ index (datasource "input").cluster.environment }}-fluxsystem
  interval: 5m
  values:
    image: "istio_helper:v0.0.19"

    imagePullSecrets:
      - name: image-creds

    # Service account will be deployed as part of bootstrap support chart
    serviceAccountName: "isttiobootstrapsvc"

    # Kubernetes cluster name
    clustername: {{ index (datasource "input").cluster.name }}
