---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      version: 1-24-2-tetrate-v2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: infrastructure-qa-fluxsystem
  interval: 5m
  values:
    defaultRevision: 1-24-2